name: graphql_example
description: "GraphQL example project using Flutter."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  app_links: ^6.1.1
  bloc: ^8.1.4
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  flutter_web_auth: ^0.5.0
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  graphql_flutter: ^5.1.2
  intl: ^0.19.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  logger: ^2.3.0
  meta: ^1.12.0
  path_provider: ^2.1.3
  sign_in_button: ^3.2.0
  svg_flutter: ^0.0.1

dev_dependencies:
  build_runner: ^2.4.11
  built_value_generator: ^8.9.2
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/fonts/
    - assets/icons/
  fonts:
    - family: Kanit
      fonts:
        - asset: assets/fonts/Kanit-Regular.ttf
        - asset: assets/fonts/Kanit-SemiBold.ttf
          weight: 400
        - asset: assets/fonts/Kanit-SemiBoldItalic.ttf
          style: italic
          weight: 400

flutter_intl:
  enabled: true

flutter_assets:
  assets_path: assets/
  output_path: lib/generated/
  filename: assets.dart
