name: graphql_example
description: "GraphQL example project using Flutter."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  app_links: ^6.1.1
  bloc: ^8.1.4
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  flutter_web_auth: ^0.5.0
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logger: ^2.3.0
  meta: ^1.12.0
  sign_in_button: ^3.2.0
  svg_flutter: ^0.0.1

dev_dependencies:
  build_runner: ^2.4.10
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
flutter_intl:
  enabled: true

flutter_assets:
  assets_path: assets/
  output_path: lib/generated/
  filename: assets.dart
